apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-home-etc-ibcf  
spec:
  volumeName: pv-home-etc-ibcf
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

